function out1 = Pendulum_2_Lag_Num_Raw(L1,L2,g,m1,m2,th1,th2,thD1,thD2)
%PENDULUM_2_LAG_NUM_RAW
%    OUT1 = PENDULUM_2_LAG_NUM_RAW(L1,L2,G,M1,M2,TH1,TH2,THD1,THD2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    19-Oct-2017 23:29:55

t2 = L1.^2;
t3 = cos(th1);
t4 = sin(th1);
t5 = t3.^2;
t6 = t4.^2;
t7 = cos(th2);
t8 = L1.*L2.*t3.*t7;
t9 = sin(th2);
t10 = L1.*L2.*t4.*t9;
t11 = t8+t10;
t12 = m2.*t11.*(1.0./2.0);
t13 = L2.^2;
t14 = th1-th2;
t15 = sin(t14);
out1 = reshape([m1.*t2.*(1.0./1.2e1)+m2.*(t2.*t5.*2.0+t2.*t6.*2.0).*(1.0./2.0)+m1.*(t2.*t5.*(1.0./2.0)+t2.*t6.*(1.0./2.0)).*(1.0./2.0),t12,t12,m2.*t13.*(1.0./1.2e1)+m2.*(t7.^2.*t13.*(1.0./2.0)+t9.^2.*t13.*(1.0./2.0)).*(1.0./2.0),L1.*(g.*m1.*t4+g.*m2.*t4.*2.0+L2.*m2.*t15.*thD2.^2).*(1.0./2.0),L2.*m2.*(g.*t9-L1.*t15.*thD1.^2).*(1.0./2.0)],[2,3]);
