function out1 = Pendulum_2_AMB_Num_Raw(L1,L2,g,m1,m2,th1,th2,thD1,thD2)
%PENDULUM_2_AMB_NUM_RAW
%    OUT1 = PENDULUM_2_AMB_NUM_RAW(L1,L2,G,M1,M2,TH1,TH2,THD1,THD2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    19-Oct-2017 23:12:51

t2 = L1.^2;
t3 = th1-th2;
t4 = cos(t3);
t5 = sin(th1);
t6 = sin(t3);
t7 = L1.*L2.*m2.*t4.*(1.0./2.0);
t8 = sin(th2);
t9 = thD1.^2;
out1 = reshape([t7+m1.*t2.*(1.0./3.0)+m2.*t2,t7,L2.*m2.*(L2.*2.0+L1.*t4.*3.0).*(1.0./6.0),L2.^2.*m2.*(1.0./3.0),L1.*g.*m1.*t5.*(1.0./2.0)+L1.*g.*m2.*t5+L2.*g.*m2.*t8.*(1.0./2.0)-L1.*L2.*m2.*t6.*t9.*(1.0./2.0)+L1.*L2.*m2.*t6.*thD2.^2.*(1.0./2.0),L2.*m2.*(g.*t8.*2.0-L1.*t6.*t9.*2.0).*(1.0./4.0)],[2,3]);
